import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import "./globals.css";

export const metadata: Metadata = {
  title: "RedLightGreenLight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
  appearance={{
   theme: dark,
  }}
>
  <html lang="en">
    <body>{children}</body>
  </html>
</ClerkProvider>

  );
}
